#!/bin/zsh
# common zsh aliases and env var

if [ -f ~/.zshenv.work ]; then
  source ~/.zshenv.work
fi

#--------------------
# directories aliases
#--------------------

#--------------------
# env var
#--------------------


