#! /bin/zsh

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# If this is an xterm set the title to user@host:dir
case "$TERM" in
  xterm*|rxvt*)
    precmd () {print -Pn "\e]0;%n@%m: %~\a"}
    ;;
  *)
    ;;
esac

#--------
# History
#--------

# history file
export HISTFILE=$HOME/.history

# number of entries in history
export HISTSIZE=1000
export HISTORY=10000
export SAVEHIST=10000

# directly add line in history
setopt inc_append_history

# share history between all sessions
#setopt share_history extended_history

# if a line has been entered more than once, keep only the last occurrence
setopt hist_ignore_all_dups

# make search up and down work, so partially type and hit up/down
# to find  relevant stuff
autoload -U up-line-or-search
autoload -U down-line-or-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey 'OA' up-line-or-search
bindkey 'OB' down-line-or-search
bindkey '[A' up-line-or-search
bindkey '[B' down-line-or-search
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

#-------
# Prompt
#-------

autoload -U colors
colors

#Did it because of a trailing %, but sometimes it causes the disparition of the
#last line after executing a command, e.g. curl response body
#unsetopt PROMPT_SP

#function prompt_char {
#  git branch >/dev/null 2>/dev/null && echo '☿' && return
#  hg root >/dev/null 2>/dev/null && echo 'λ' && return
#  echo '○'
#}

#source $HOME/.zsh/zsh-git-prompt/zshrc.sh

#PROMPT='${debian_chroot:+($debian_chroot)}\[\\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

PROMPT="%B%F{green}%n@%m%f%F{black}:%f%F{blue}%2~%f%b$ "
#PROMPT="%F{cyan}%n%f%F{red}@%m %f%F{red}%2~%f"'$(git_super_status)'" "
#%T"' $(prompt_char) '"%f%b"

#this version uses a different color (blue) for privileged user
#PROMPT="%(!.%F{blue}.%F{cyan})%n%f%F{red}@%m %f%F{red}%~%f"'$(git_super_status)'"
#%T"' $(prompt_char) '"%f%b"

#if [ $UID -eq 0 ] ; then
##color commands in red for root
#source /etc/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
#else
##color commands in green for non-root
#source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)

#fi

RPROMPT=""

# custom zsh-git-prompt
ZSH_THEME_GIT_PROMPT_PREFIX=" "
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_SEPARATOR=" "
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}%{●%G%}"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg_bold[red]%}%{✖%G%}"
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[black]%}%{✚%G%}"
ZSH_THEME_GIT_PROMPT_BEHIND=" %{↓%G%}"
ZSH_THEME_GIT_PROMPT_AHEAD=" %{↑%G%}"
ZSH_THEME_GIT_PROMPT_UNTRACKED=" %{$fg[black]%}%{…%G%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[green]%}%{✔%G%}"

autoload -U promptinit
promptinit

#------------
# Misc configs
#------------

# vi-mode
#set -o vi

# emacs-bind
bindkey -e

# propose a correction if a typo error is detected
setopt nocorrectall
setopt correct

#-------------------------------
# Aliases, environment variables
#-------------------------------

# os specific
if [ -f ~/.zprofile ]; then
  source ~/.zprofile
fi

if [ -f ~/.xprofile ]; then
  source ~/.xprofile
fi

# path
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# commands
alias df="df -h"
alias du="du -hs"
alias etchosts="sudo vim /etc/hosts"
alias :e="vim"
alias :q="exit"
alias ll='ls -alh'
alias vi="nvim"
alias vim="nvim"
alias view="nvim -R"
alias vimdiff="nvim -d"

#-----------
# Completion
#-----------

autoload -Uz compinit
compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# edit command line in vim
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# asdf
. "$HOME/.asdf/asdf.sh"
fpath=(${ASDF_DIR}/completions $fpath)
autoload -Uz compinit && compinit
export ASDF_DATA_DIR="$HOME/.asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"

# direnv
eval "$(direnv hook zsh)"

# erlang shell history
export ERL_AFLAGS="-kernel shell_history enabled"

# elixir compilation
# run deps compilation in multiple cores
local n_cpu="$(( $(nproc) / 2 ))"
export MIX_OS_DEPS_COMPILE_PARTITION_COUNT="$n_cpu"

# aliases

alias git_merge_back_master_to_develop='git checkout master;git pull; git checkout develop; git pull; git merge --no-ff --no-edit master;git push origin develop'
alias sshblancheneige='ssh -i ~/.ssh/id_rsa ec2-user@54.171.21.129'
alias sshkibana='ssh -i ~/.ssh/awfus_ie.pem ubuntu@52.48.66.82'
alias sshdokku='ssh dokku'
alias psql-digiforma-local='psql "host=db-digiforma-prod.ch6qqqq6mewh.eu-west-1.rds.amazonaws.com port=5432 dbname=digiforma user=vRvKq6XZxh4YKYfaDimu sslmode=verify-full sslrootcert=~/.ssh/global-bundle.pem"'
alias psql-digiforma-prod='psql "$(doppler secrets get --project digiforma --config prd --plain DATABASE_URL)"'
alias psql-digiforma-staging='psql "$(doppler secrets get --project digiforma --config stg --plain DATABASE_URL)"'
#alias psql-digiforma-staging='psql -U adm1rtin -d digiforneige -p 5432 -h blanche-neige-staging.cnkq40kaocis.eu-west-1.rds.amazonaws.com'
alias psql-digiforma-rainbowdash='psql -U adm1rtin -d digiforneige -p 5432 -h blanche-neige-rainbowdash.cnkq40kaocis.eu-west-1.rds.amazonaws.com'
alias psql-identity-prod='psql "$(doppler secrets get --project digiforma-identity --config prd --plain DATABASE_URL)"'
alias psql-identity-staging='psql "$(doppler secrets get --project digiforma-identity --config stg --plain DATABASE_URL)"'
alias digiforma-bn='doppler run --preserve-env -- iex -S mix phx.server'
alias digiforma-local='USE_BLANCHE_NEIGE=false doppler run --preserve-env -- iex -S mix phx.server'
alias digiforma-prod='heroku run "/opt/app/bin/digiforma start_iex" -a digiforma'
alias digiforma-staging='heroku run "/opt/app/bin/digiforma start_iex" -a digiforma-staging'
alias identity-local='doppler run --preserve-env -- iex -S mix phx.server'
alias identity-prod='heroku run "PHX_SERVER=true exec /app/bin/app start_iex" -a digiforma-identity-prod'
alias identity-staging='heroku run "PHX_SERVER=true exec /app/bin/app start_iex" -a digiforma-identity-staging'
alias extranet='doppler run -- npm start'
alias bnpassword='doppler secrets get BLANCHE_NEIGE_URL --json'
alias bnimport='USE_BLANCHE_NEIGE=false doppler run --preserve-env -- mix import_academy_data'
alias bnexport="cd ~/Code/digiforma-academies-dump; doppler run --preserve-env --command='docker run -e DOPPLER_TOKEN=\${DOPPLER_TOKEN} -e ACADEMY_IDS=\${ACADEMY_IDS} -v $(pwd)/dumps:/app/dumps digiforma-academies-dump'"
alias dbreset='USE_BLANCHE_NEIGE=false doppler run --preserve-env -- mix ecto.reset'

export CODE_DIR="$HOME/Code"
alias cdcode="cd $CODE_DIR"
alias cddigiforma="cd $CODE_DIR/digiforma"
alias cdidentity="cd $CODE_DIR/digiforma-identity"
alias cddocgen="cd $CODE_DIR/docgen"
alias cdextranet="cd $CODE_DIR/extranet"
alias cdk6="cd $CODE_DIR/k6"

alias doppler-enable-identity='doppler configs update --inherits digiforma.dev_feat_digiforma_identity'
alias doppler-enable-kibana='doppler configs update --inherits digiforma.dev_feat_kibana'
alias doppler-enable-grafana-local='doppler configs update --inherits digiforma.dev_feat_grafana_local'
alias doppler-clear-inheritance='doppler configs update --project proj --config dev --inherits='
