#!/bin/bash

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install caskroom/cask/brew-cask
brew update --cask

#shell
brew install --cask iterm2

#text editor
#brew install vim
brew install --cask macvim --override-system-vim
brew linkapps macvim

#gpg
brew install gpg2
brew install --cask gpgtools

#network
brew install curl
brew install wget
#brew install --cask tunnelblick
#brew install --cask opera
#brew install --cask thunderbird
#brew install --cask google-hangouts
#brew install --cask adium
#brew install --cask skype
#brew install --cask dropbox
#brew install --cask utorrent

#dev
brew install git
#brew install golang
brew install cmake
brew install ctags
brew install node
#brew install --cask nwjs
#sudo easy_install pip

#virtualization
#brew install ansible
#brew install --cask virtualbox
#brew install --cask vagrant
#brew install --cask vagrant-manager

#draw
#brew install --cask gimp
#brew install --cask xquartz
#brew install --cask inkscape

#media
#brew install --cask vlc

#tools
brew install coreutils
#brew-install --cask osxfuse
#brew install ext4fuse
#brew install ntfs-3g
brew install htop-osx
sudo pip install glances
brew install --cask razer-synapse

#office
brew install --cask libreoffice
brew install --cask mactex

