#!/bin/bash
ARC_THEME=$DOTFILES/linux/gtk/themes/arc

apt update

# settings
apt install -y gnupg
apt install -y dconf-editor

# shell
apt install -y zsh

# text
apt install -y vim
apt install -y vim-gui-common
apt install -y neovim
apt install -y texlive
apt install -y texlive-latex-extra
apt install -y texlive-lang-french

# monitoring
apt install -y htop
apt install -y glances

# dev
apt install -y build-essential
apt install -y make
apt install -y autoconf
apt install -y cmake
apt install -y golang-go

# media
apt install -y vlc
apt install -y steam

# fonts
apt install -y fonts-dejavu
apt install -y fonts-noto

